name: ecommerce
description: "A new Flutter project for ecommerce exams with localization."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: ^0.19.0 
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.13
  video_player: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/videos/
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700